### PR TITLE
Fix/op return fail

### PR DESCRIPTION
**Pull request by lissavxo**
Related to #426 

Description
---
Fix opReturn fail behavior 

Test plan
---
create a button/widget with `op-return` prop set to a large string like this:
`"ABCDEFGHIJKLMNOPABCDEFlkfdnlkfndlksnkjsnfkldsnlknlksssssssss;sssssssssGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP"`
the expected behavior is blur QR code and show the error message in console instead of in the button text.

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
- Rebase to master.
- Can we add this (OP_RETURN msg) to the button generator?

**Review by chedieck — CHANGES_REQUESTED** [review]
The behavior described in the test plan checks out, however, the issue mentions reverting the text back, not getting ridding of it and using the console.

I don't think showing the error in the console only is a good idea, I think we should display that same text of before but having it cleared out after 5s (as we do in other places).

The color could be red to indicate an error, too.

**Review by chedieck — APPROVED** [review]

**Review by Klakurka — CHANGES_REQUESTED** [review]
After a few seconds, the text at the top changes from the red error to "send any amount":

image

I get that this is kinda out of scope and related to #327 but IMO we should just deal with this now. Up to you if you want to do it in this branch or a new one.

**Review by chedieck — APPROVED** [review]
> After a few seconds, the text at the top changes from the red error to "send any amount":

I thought this was the desired behavior, as per the issue description.

In any case, I also think is better to leave the error there.

**Comment by Klakurka** [comment]
> > After a few seconds, the text at the top changes from the red error to "send any amount":
> 
> I thought this was the desired behavior, as per the issue description.
> 
> In any case, I also think is better to leave the error there.

It's referring to when the widget is regenerated.

**Review by Klakurka — DISMISSED** [review]
We can improve the error message at some point as the wording is pretty technical but it's fine for now.

**Review by Klakurka — APPROVED** [review]

**Review by Klakurka — APPROVED** [review]

**Review by chedieck — APPROVED** [review]

**Pull request merged**
