### PR TITLE
feat: onSuccess and onTransaction do not fire both

### PR DESCRIPTION
**Pull request by chedieck**
Depends on
---
- [ ] #268

Description
---
Changes so that the behavior of the `onSuccess` and `onTransaction` functions is:
`onSuccess`: fires if the incoming transaction amount is the same of the button. If no amount is set, never fires.
onTransaction: fires in all other cases

Test plan
---
Check that the behavior described above is correct for buttons with or without amount.

### CODE REVIEW

**Comment by Klakurka** [comment]
We'll need to update the docs too.

**Review by Klakurka — CHANGES_REQUESTED** [review]
I can only get Transaction to fire.

**Comment by chedieck** [comment]
> I can only get Transaction to fire.

I forgot to add the other branch to it, updated as a dependency, should work now.

**Review by Klakurka — CHANGES_REQUESTED** [review]
I can still only get on-transaction to fire.

**Pull request merged**
