### PR TITLE
feat:enable altpayment prop

### PR DESCRIPTION
**Pull request by lissavxo**
Related to #422 

Description
---
Created a new prop to enable altpayment logic 

Test plan
---
Create a widget or a paybutton and test prop enable-altpayment="true" and enable-altpayment="false", this prop should control the sideshift logic, it should work on paybutton and widget

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
Doesn't build for me:

image

**Review by Klakurka — CHANGES_REQUESTED** [review]
Can you add an entry into the docs? All 3 langs.

**Review by Klakurka — CHANGES_REQUESTED** [review]
On the Chinese docs, the desc format is different from what we have on the other properties:

image
image

Can you use the same tags & quotes as we're using on the other ones to keep them consistent?

**Review by Klakurka — APPROVED** [review]

**Review by Klakurka — CHANGES_REQUESTED** [review]
Actually can you add this into `paybutton-generator.html` ?

**Review by chedieck — CHANGES_REQUESTED** [review]
Adding `enable-altpayment="false"` doesn't seem to work at the buttons / widgets of paybutton/dev/demo/index.html

**Review by Klakurka — APPROVED** [review]

**Review by chedieck — APPROVED** [review]
After running `yarn clean:build`, it worked out well

**Pull request merged**
