### PR TITLE
feat: add dev page

### PR DESCRIPTION
**Pull request by lissavxo**
Related to #382 

Description
---
Created a dev test html with more button options and some widgets 
Updated the configurations of rollup dev to serve the new dev page and also save bundle file inside of the demo folder to make it easier to serve 

Test plan
---
Run `yarn build` and` cd paybutton && yarn dev`, the dev page should have more button options and widgets

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
- Can you update the docs site w/ the proper instructions too?
- image
- Something crazy going on w/ the loading spinner position: 
image
- Would be nice if the custom buttons at least used the pointer cursor when hovering.

**Review by Klakurka — CHANGES_REQUESTED** [review]
- Let's have the custom buttons use the pointer cursor when hovering.
- If we're going to change the formatting on the docs page, the Website / Documentation bit needs it too.

**Review by Klakurka — CHANGES_REQUESTED** [review]
Change all XEC addresses to use `qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7quss2vxek`.

The BCH address is fine.

**Review by Klakurka — APPROVED** [review]

**Review by chedieck — CHANGES_REQUESTED** [review]
Looks good, only issue I found was the creation of unstaged files:
изображение


Maybe add it to .gitignore?

**Review by chedieck — APPROVED** [review]

**Review by Klakurka — APPROVED** [review]

**Pull request merged**
