### PR TITLE
chore: Better compiling config

### PR DESCRIPTION
**Pull request by chedieck**
Description
---
Better config to dev, makes it so that it takes 40s to compile it in my machine instead of 10m.

Test plan
---
Before, running `npm run start` on the `paybutton/` folder should take significantly longer than running (now renamed to `npm run dev`) it now.

 
Remarks
---
Makes so that we don't minimify it and remove comments on the output JS file if running `npm run dev`. This is only useful for production, so we only do it on production.

### CODE REVIEW

**Comment by chedieck** [comment]
> What would be the command for prod?

`npm run build`. Should be unaltered.

**Review by Klakurka — CHANGES_REQUESTED** [review]
Can you try merging master into this?

**Review by Klakurka — CHANGES_REQUESTED** [review]
There's some performance issues loading HTML buttons when using this. Anything you want to do about it? The prod npm build is fine.

**Comment by chedieck** [comment]
> Can you try merging master into this?

Done

**Review by Klakurka — APPROVED** [review]
OK so the issue is that livereload is timing out after 20s on the server I'm running it on which I don't think is a big deal.

**Pull request merged**
