### PR TITLE
Fix/disabled prop

### PR DESCRIPTION
**Pull request by lissavxo**
Related to #420 

Depends on
---
- [x] #423 

Description
---
Fix widget and button being disabled when the prop is "false"  

Test plan
---
Run yarn `clean:build && yarn dev` , go to the generator page and test the disabled prop

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
1. Go to http://localhost:10001/paybutton-generator.html
2. Set disabled = true
3. Click 'Generate'
4. Test button (it'll be disabled)
5. Set disabled = false
6. Click 'Generate'
7. See that it's still disabled (it should be enabled)

**Comment by lissavxo** [comment]
> 1. Go to http://localhost:10001/paybutton-generator.html
> 2. Set disabled = true
> 3. Click 'Generate'
> 4. Test button (it'll be disabled)
> 5. Set disabled = false
> 6. Click 'Generate'
> 7. See that it's still disabled (it should be enabled)

Fixed

**Review by Klakurka — CHANGES_REQUESTED** [review]
The generator is just very broken for me with this build.

Not much seems to apply properly when clicking 'Generate'. `Disabled` definitely doesn't work at all.

Master works fine though so there's something going on with this one.

**Review by Klakurka — APPROVED** [review]
Seems to work now but I noticed that the `theme` doesn't apply in the generator.

**Comment by Klakurka** [comment]
Conflicts.

**Review by chedieck — APPROVED** [review]
LGTM

**Pull request merged**
