### PR TITLE
fix: rollup issues breaking builds on master

### PR DESCRIPTION
**Pull request by alcipir**
Description: (pending issue), bump some dependency versions and tune some config options in order to build a usable version on Windows and Unix-like systems.

Test Plan: run `cd react && npm i && npm run build && cd ../paybutton && npm i && npm run build`, and test it out on a single HTML file, like: 
```

<html>
  <body>
    <div class="paybutton" to="bitcoincash:qrmm7edwuj4jf7tnvygjyztyy0a0qxvl7q9ayphulp"></div>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script
      src="dist/paybutton.js"
    ></script>

  </body>
</html>
```

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
Can't get passed building the React version:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @paybutton/react@1.1.0
npm WARN Found: @types/react@16.14.28
npm WARN node_modules/@types/react
npm WARN   dev @types/react@"^18.0.20" from the root project
npm WARN   9 more (@material-ui/core, @material-ui/lab, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional @types/react@"^16.8.6 || ^17.0.0" from @material-ui/core@4.12.4
npm WARN node_modules/@material-ui/core
npm WARN   @material-ui/core@"4.12.4" from the root project
npm WARN   2 more (@material-ui/lab, notistack)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @paybutton/react@1.1.0
npm WARN Found: @types/react@16.14.28
npm WARN node_modules/@types/react
npm WARN   dev @types/react@"^18.0.20" from the root project
npm WARN   9 more (@material-ui/core, @material-ui/lab, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional @types/react@"^16.8.6 || ^17.0.0" from @material-ui/core@4.12.4
npm WARN node_modules/@material-ui/core
npm WARN   @material-ui/core@"4.12.4" from the root project
npm WARN   2 more (@material-ui/lab, notistack)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @paybutton/react@1.1.0
npm WARN Found: @types/react@16.14.28
npm WARN node_modules/@types/react
npm WARN   dev @types/react@"^18.0.20" from the root project
npm WARN   9 more (@material-ui/core, @material-ui/lab, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional @types/react@"^16.8.6 || ^17.0.0" from @material-ui/core@4.12.4
npm WARN node_modules/@material-ui/core
npm WARN   @material-ui/core@"4.12.4" from the root project
npm WARN   2 more (@material-ui/lab, notistack)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @paybutton/react@1.1.0
npm WARN Found: @types/react@16.14.28
npm WARN node_modules/@types/react
npm WARN   dev @types/react@"^18.0.20" from the root project
npm WARN   9 more (@material-ui/core, @material-ui/lab, ...)
```

etc etc

**Comment by Klakurka** [comment]
```
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\David\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\X\AppData\Local\npm-cache\_logs\2022-09-26T22_12_59_289Z-debug-0.log
```

**Comment by Gattaca1** [comment]
Looks like I get the same errors as David
Screenshot from 2022-09-27 13-19-46

**Comment by Gattaca1** [comment]
I can get this branch running by adding `--legacy-peer-deps` to the run command. That allows it to build, however storybook still fails to run, and that looks like its a webpack5 compatibility issue (storybook just straight up is not compatible with webpack5)

**Comment by Klakurka** [comment]
Superseded by https://github.com/PayButton/paybutton/pull/171

**Pull request closed without merging**
