### PR TITLE
feat: sideshift integration

### PR DESCRIPTION
**Pull request by chedieck**
Related to #187

Description
---
Adds logic to select coins using SideShift's API, displays their amount and the rate of conversion. 

This PR adds the logic for selecting the amount & currency to pay with, but **it doesn't yet implement the payment itself.** 

E.g, by selecting BTC and clicking "Pay with BTC", nothing will happen aside from a console.log of "WIP".

It's also important to notice that I didn't work in the design of the components, only their functionality. This PR lays ground for a frontend work to be done, with the goal of making the new  stuff more intuitive and agreeable for the eyes. 

Finally, it is also important to notice that this PR is off of a proxy branch, meaning approving and merging it won't commit anything to master (since it's incomplete). Nonetheless, it should be reviewed as if the changes here proposed are good enough (in what they propose to address) to eventually go to master (when all the changes are complete).

Test plan
---
For editable and non-editable paybuttons, there should be a "Don't have any XEC?" text which upon clicking will allow the user to select an alternative cryptocurrency to pay with.

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
Can't seem to get this to build.

image

**Review by Klakurka — CHANGES_REQUESTED** [review]
- Don't allow people to select the same currency that they're paying to (eg. XEC).

**Comment by chedieck** [comment]
> * Don't allow people to select the same currency that they're paying to (eg. XEC).

addressed.

**Review by Klakurka — APPROVED** [review]

**Comment by Klakurka** [comment]
This is one of those situations where it would have been good to put this behind a "feature flag" but I'm also ok just merging it as-is. If we had a bit more going on where we'd want to deploy some other feature/fix before this went live, we'd definitely want that flag there to be able to switch it on once it's actually ready.

**Pull request merged**
