### PR TITLE
extracted dialog component and created openDialog function

### PR DESCRIPTION
**Pull request by gnarj**
payment dialog can be rendered independent of button by calling openDialog({ to: 'address' })

### CODE REVIEW

**Comment by Klakurka** [comment]
Can you add a test/example into both Storybook and rollup?

It'll allow us to more easily test this both now and in the future.

**Review by Klakurka — CHANGES_REQUESTED** [review]
Can you add a test/example into both Storybook and rollup?

It'll allow us to more easily test this both now and in the future.

**Comment by gnarj** [comment]
@Klakurka added those examples/tests to the rollup and storyboard. if you have any requests on the storyboard examples, i am happy to add them.

**Review by Klakurka — CHANGES_REQUESTED** [review]
We decided that we're going to refactor this a bit but functionality looks good.

**Pull request merged**
