### PR TITLE
[#302] Refactor: rename nonce -> paymentId

### PR DESCRIPTION
**Pull request by chedieck**
Related to #302

Depends on
---
- [x] #341
- [x] #345

Description
---
Simple refactor, renames `nonce` to `paymentId` everywhere to avoid having two names for the same things since we use `paymentId` in the props and in the server.

Test plan
---
Nothing should change.

### CODE REVIEW

**Review by Klakurka — CHANGES_REQUESTED** [review]
I changed the payment ID option description in English. Can you re-do the Chinese translations for those? Try to keep the formatting the same as the other examples.

Also I'd prefer if the 'disable' options are all together so maybe worth moving it down.

**Comment by chedieck** [comment]
> I changed the payment ID option description in English. Can you re-do the Chinese translations for those? Try to keep the formatting the same as the other examples.
> 
> Also I'd prefer if the 'disable' options are all together so maybe worth moving it down.

This would probably best have been done in [the other PR](https://github.com/PayButton/paybutton/pull/341); nonetheless all addressed.

**Review by Klakurka — APPROVED** [review]
Yep -- I realized after moving on from this one.

**Review by Klakurka — DISMISSED** [review]

**Comment by chedieck** [comment]
To facilitate review I created https://github.com/PayButton/paybutton/pull/345 that should be reviewed and merged first to make the diff here only account for the string substitution related to the PR.

**Review by Klakurka — APPROVED** [review]

**Pull request merged**
